const product = [
  "Smartphone",
  "Laptop",
  "Smartwatch",
  "Bluetooth Earphones",
  "4K TV",
  "Gaming Console",
  "Wireless Mouse",
  "Digital Camera",
  "Fitness Tracker",
  "Portable Bluetooth Speaker",
  "Tablet",
  "Headphones",
  "External Hard Drive",
  "Virtual Reality Headset",
  "Drone",
  "Smart Home Hub",
  "Smart Thermostat",
  "E-book Reader",
  "Wireless Charger",
  "Action Camera",
  "Graphics Card",
  "Smart Bulbs",
  "Robot Vacuum Cleaner",
  "Wireless Keyboard",
  "Noise-Canceling Earbuds",
  "Fitness Smart Scale",
  "Smart Doorbell",
  "Electric Toothbrush",
  "Power Bank",
  "Gaming Mouse",
  "VR Gaming Headset",
  "Smart Refrigerator",
  "Bluetooth Keyboard",
  "Wireless Security Camera",
  "Smart Mirror",
  "Wireless Headset for Gaming",
  "Digital Drawing Tablet",
  "Bluetooth Gaming Controller",
  "Mini Projector",
  "Portable Monitor",
  "Smart Humidifier",
  "Smart Oven",
  "Smart Coffee Maker",
  "Wireless Gaming Router",
  "3D Printer",
  "Solar Power Bank",
  "Smart Baby Monitor",
  "Fitness Smart Shirt",
];

const descriptions = [
  "Cutting-edge smartphone with a high-resolution display and advanced camera features.",
  "Sleek and powerful laptop for work and entertainment on the go.",
  "Fashionable smartwatch combining fitness tracking, notifications, and style.",
  "Wireless earphones with Bluetooth connectivity for tangle-free listening.",
  "Immersive 4K TV providing stunning visuals and a cinematic viewing experience.",
  "Gaming console with a vast library of games for hours of entertainment.",
  "Wireless mouse for convenient and precise computer navigation.",
  "Compact digital camera capturing sharp images and videos.",
  "Fitness tracker monitoring activity, sleep, and overall health.",
  "Portable Bluetooth speaker delivering high-quality sound for any occasion.",
  "Versatile tablet with a touchscreen interface for various applications.",
  "High-quality headphones for an immersive audio experience.",
  "External hard drive for reliable data backup and additional storage.",
  "Virtual reality headset for an immersive and interactive experience.",
  "Aerial drone for capturing breathtaking photos and videos from above.",
  "Smart home hub for central control and automation of smart devices.",
  "Intelligent thermostat for energy-efficient and automated temperature control.",
  "E-book reader for a portable and convenient digital reading experience.",
  "Wireless charger for hassle-free and cable-free device charging.",
  "Action camera capturing adventurous moments with durability.",
  "Graphics card for high-performance rendering in gaming and design.",
  "Smart bulbs providing energy-efficient and customizable lighting.",
  "Robot vacuum cleaner autonomously cleaning floors with precision.",
  "Wireless keyboard for flexible and clutter-free computer usage.",
  "Noise-canceling earbuds delivering crystal-clear audio in any environment.",
  "Fitness smart scale measuring weight and essential health metrics.",
  "Smart doorbell with a built-in camera for enhanced home security.",
  "Electric toothbrush for effective and automated oral care.",
  "Portable power bank for charging devices on the go.",
  "Gaming mouse designed for precision and responsiveness in gaming.",
  "VR gaming headset for an immersive and thrilling gaming experience.",
  "Smart refrigerator with advanced features for modern living.",
  "Bluetooth keyboard for wireless and comfortable typing.",
  "Wireless security camera for remote monitoring and surveillance.",
  "Smart mirror displaying information like weather and fitness metrics.",
  "Wireless headset for gaming with advanced audio features and comfort.",
  "Digital drawing tablet for artists to create artwork digitally.",
  "Bluetooth gaming controller for wireless and responsive gaming control.",
  "Mini projector for a compact and portable big-screen experience.",
  "Portable monitor for additional screen space on the go.",
  "Smart humidifier maintaining optimal humidity levels with smart features.",
  "Smart oven with precise cooking features for convenience.",
  "Smart coffee maker with automation and remote control capabilities.",
  "Wireless gaming router for high-performance gaming connectivity.",
  "3D printer creating three-dimensional objects from digital models.",
  "Solar power bank charging devices with eco-friendly solar energy.",
  "Smart baby monitor with video streaming and alerts for peace of mind.",
  "Fitness smart shirt with embedded sensors for tracking workout metrics.",
  "Customizable electronic item description. Replace this placeholder.",
  "Customizable electronic item description. Replace this placeholder.",
];

const prices = [
  799.99, 1299.99, 199.99, 79.99, 1499.99, 399.99, 29.99, 499.99, 129.99, 79.99,
  349.99, 199.99, 89.99, 299.99, 999.99, 149.99, 199.99, 129.99, 59.99, 299.99,
  499.99, 599.99, 349.99, 199.99, 249.99, 299.99, 79.99, 129.99, 49.99, 59.99,
  69.99, 399.99, 799.99, 1499.99, 99.99, 149.99, 799.99, 129.99, 199.99, 499.99,
  249.99, 349.99, 299.99, 79.99, 499.99, 129.99, 89.99, 299.99, 799.99, 59.99,
];

const url =
  "https://www.creativefabrica.com/wp-content/uploads/2021/04/28/Work-In-Progress-Rubber-Stamp-Vector-Graphics-11432494-1.jpg";

module.exports = { product, descriptions, prices, url };
